perception_node: # Name of Node
  ros__parameters:
    left_camera_topic: "/left_camera_node/images/compressed"
    right_camera_topic: "/right_camera_node/images/compressed"
    cone_detections_topic: "perception/cone_detections"
    processed_lidar_topic: "/lidar_pipeline/detected"
    baseline: 10.0
    update_rate: 33.0 #[ms]
    distortion_left: [-0.2632632062603271, 0.12474952835752845, 0.0, 0.0, 0.0]
    distortion_right: [-0.269633921151086, 0.12944192627838266, 0.0, 0.0, 0.0]
    intrinsics_left:
      [
        1176.4720209159348,
        0.0,
        717.3175336097887,
        0.0,
        1176.4502103799837,
        555.1127066183973,
        0.0,
        0.0,
        1.0,
      ]
    intrinsics_right:
      [
        1169.929054195447,
        0.0,
        732.7234047220617,
        0.0,
        1168.6955521426203,
        539.5227062057302,
        0.0,
        0.0,
        1.0,
      ]
    rotation:
      [
        0.9948,
        -0.0030,
        -0.1020,
        0.0040,
        0.9999,
        0.0094,
        0.1020,
        -0.0097,
        0.9947,
      ]
    translation: [-516.6818, 29.1172, -386.7437]
    rectify_left:
      [
        0.999933395,
        0.000876606484,
        0.0115081202,
        -0.000858846762,
        0.999998433,
        -0.00154808535,
        -0.0115094592,
        0.00153809852,
        0.999932581,
      ]
    rectify_right:
      [
        0.99986953,
        -0.00121598,
        0.01610718,
        0.00119112,
        0.99999809,
        0.00155276,
        -0.01610904,
        -0.00153337,
        0.99986907,
      ]
    save_pic: "False"
    confidence: 0.40
    cone_heights: [0.0, 325.0, 325.0, 325.0, 505.0]
    lidar_only_detection: False

    # shopping cart
    # intrinsics_left:
    #   [1154.0316, 0.0, 735.5679, 0.0, 1149.3709, 556.7507, 0.0, 0.0, 1.0]
    # intrinsics_right:
    #   [1152.2591, 0.0, 738.7035, 0.0, 1147.0141, 560.6309, 0.0, 0.0, 1.0]
    # rotation: [1.0, 0.002, -0.0046, -0.0021, 1.0, -0.0031, 0.0046, 0.0031, 1.0]
    # translation: [-352.5918, 0.4288, -5.68]

    # # on car rectify:
    # rectify_left:
    #   [
    #     0.85645177,
    #     -0.05329929,
    #     0.51346816,
    #     0.05183408,
    #     0.99850776,
    #     0.01718969,
    #     -0.51361814,
    #     0.01189301,
    #     0.85793646,
    #   ]
    # rectify_right:
    #   [
    #     0.79975706,
    #     -0.04506969,
    #     0.59862957,
    #     0.04680415,
    #     0.99882373,
    #     0.01267014,
    #     -0.59849646,
    #     0.01788531,
    #     0.80092578,
    #   ]

lidar_proc_node:
  ros__parameters:
    update_rate: 33.33 #[ms]
    debug: True
    topics: # TODO: fix
      input: "/ouster/points"
      filtered: "/lidar_pipeline/filtered"
      no_ground: "/lidar_pipeline/no_ground"
      clustered: "/lidar_pipeline/clustered"
      detected: "/lidar_pipeline/detected"
      heartbeat: "/lidar_pipeline/heartbeat"
    view_filter:
      outer_box: #remove all points outside of outer box
        xmin: 0.0
        xmax: 50.0
        ymin: -5.0
        ymax: 5.0
      inner_box: #remove all points within inner box
        xmin: -1.013
        xmax: 2.1
        ymin: -0.8
        ymax: 0.8
      grid_size_x: 40 #create grid of lowest z points for each cell in grid
      grid_size_y: 40
    ground_ransac: #use z points for ransac
      max_iterations: 300
      distance_threshold: 0.15
    clustering:
      cluster_tolerance: 0.15
      min_cluster_size: 2 #3
      max_cluster_size: 200
      reconstruct_radius: 0.1 #0.25
    cone_filter:
      cone_height: 0.52
      cone_radius: 0.16
      mse_threshold: 0.00003 #any point as close as threshold is inlier
      lin_threshold: 0.022
