perception_node: # Name of Node
  ros__parameters:
    # left_camera_topic: "/left_camera_node/images/compressed"
    # right_camera_topic: "/right_camera_node/images/compressed"
    left_camera_topic: "synced_left_image"
    right_camera_topic: "synced_right_image"
    cone_detections_topic: "perception/cone_detections"
    processed_lidar_topic: "/lidar_pipeline/detected"
    baseline: 10.0
    camera_capture_rate: 33.0 #[ms]
    heartbeat_rate: 33.0 #[ms]
    debug: True
    distortion: [-0.363003, 0.113201, -0.000775, 0.000498, 0.000000]
    intrinsics:
      [
        974.649342,
        0.000000,
        655.141605,
        0.000000,
        975.211285,
        340.068068,
        0.000000,
        0.000000,
        1.000000,
      ]
    rotation: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    translation: [-516.6818, 29.1172, -386.7437]
    rectify: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    save_pic: "False"
    confidence: 0.40
    cone_heights: [0.0, 325.0, 325.0, 325.0, 505.0]
    lidar_only_detection: False
    is_cuda_cv: False
    is_cuda_deep: True

lidar_proc_node:
  ros__parameters:
    update_rate: 50.0 #[ms]
    debug: True
    topics: # TODO: fix
      input: "/ouster/points"
      filtered: "/lidar_pipeline/filtered"
      no_ground: "/lidar_pipeline/no_ground"
      clustered: "/lidar_pipeline/clustered"
      detected: "/lidar_pipeline/detected"
      heartbeat: "/lidar_pipeline/heartbeat"
    view_filter:
      outer_box: #remove all points outside of outer box
        xmin: 0.0
        xmax: 15.0
        ymin: -1.50
        ymax: 1.50
        # xmax: 6.0
        # ymin: -1.50
        # ymax: 1.50
      inner_box: #remove all points within inner box
        xmin: -1.013
        xmax: 2.1
        ymin: -0.8
        ymax: 0.8
      grid_size_x: 40 #create grid of lowest z points for each cell in grid
      grid_size_y: 20
    ground_ransac: #use z points for ransac
      max_iterations: 300
      distance_threshold: 0.15
    clustering:
      cluster_tolerance: 0.35
      min_cluster_size: 2 #3
      max_cluster_size: 50
      reconstruct_radius: 0.25
    cone_filter:
      cone_height: 0.387
      cone_radius: 0.075
      big_cone_height: 0.6216
      big_cone_radius: 0.11
      mse_threshold: 0.00003 #any point as close as threshold is inlier
      lin_threshold: 0.022
      IOUThreshold: 0.06
