#!/bin/bash

# Prerequisite: ROS 2 Humble installed on Ubuntu 22.04
# Installation guide: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html
# Author: Daniel Asadi
# Description: One-time script for first time repo setup
# Instructions: In dv24/ run 'bash scripts/utfr_init'

# Check if ROS 2 Humble is installed
if ! [ -d "/opt/ros/humble" ]; then
    echo "ROS 2 Humble is not installed. Please install ROS 2 Humble first."
    echo "Installation guide: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html"
    exit 1
fi

# Check if ROS 2 Humble is sourced in ~/.bashrc
if ! grep -Fxq "source /opt/ros/humble/setup.bash" ~/.bashrc; then
    echo "Adding 'source /opt/ros/humble/setup.bash' to ~/.bashrc"
    echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
    source ~/.bashrc
fi

# Init all submodules
git submodule update --init --recursive

# Update existing Packages:
echo "==========================================="
echo "=            Updating Ubuntu              ="
echo "==========================================="
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y libcgal-dev libboost-all-dev

echo "==========================================="
echo "=            Install rosdeps              ="
echo "==========================================="
sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src --rosdistro=humble -y

echo "==========================================="
echo "=            Install pip deps             ="
echo "==========================================="
pip install xgboost
pip install scikit-learn
pip install imutils
pip install xacro

echo "==========================================="
echo "=               Config sim                ="
echo "==========================================="
DIR="$(pwd)/src/utfr_sim"
echo "export EUFS_MASTER=$DIR" >> ~/.bashrc
source ~/.bashrc

echo "==========================================="
echo "=     Config colcon to ignore drivers     ="
echo "==========================================="
YAML_CONTENT=$(cat <<EOF
{
  "build":
    {
      "packages-ignore":
        [
          "arena_camera_node",
          "bluespace_ai_xsens_mti_driver",
          "ouster_msgs",
          "ros2_ouster",
          "velodyne",
          "velodyne_driver",
          "velodyne_laserscan",
          "velodyne_msgs",
          "velodyne_pointcloud",
          "launcher"
        ],
    },
  "test":
    {
      "packages-ignore":
        [
          "arena_camera_node",
          "bluespace_ai_xsens_mti_driver",
          "ouster_msgs",
          "ros2_ouster",
          "velodyne",
          "velodyne_driver",
          "velodyne_laserscan",
          "velodyne_msgs",
          "velodyne_pointcloud",
          "launcher"
        ],
    },
}
EOF
)

COLCON_CONFIG_DIR="$HOME/.colcon"
mkdir $COLCON_CONFIG_DIR
echo "$YAML_CONTENT" > $COLCON_CONFIG_DIR/defaults.yaml

echo "FYI: to use nodes under drivers/, use the Jetson Orin to avoid additional setup"
echo "You are now ready to build via 'colcon build --<options>'"
echo "After a sucessful build, run 'source install/setup.bash'"
echo "Finally you can launch with 'ros2 launch <node name> <launch file name>'"
