controls: # Name of Module
  ros__parameters:
    update_rate: 33.333 #[ms]

    #0 - no test, 1 - brakes, 2 - steering, 3 - brakes and steering, 4 - throttle test, 5 - throttle +brake, 6 - throttle + steer, 7 - brake, steer, throttle
    testing: 0

    #pid_parameters:
    steering_controller_params: [
        6.0, #p_gain
        0.0, #i_gain
        0.0, #d_gain

        -4095.0, # output_lim_lower, absolute value limit of output
        4095.0, # output_lim_upper, absolute value limit of output
      ]

    throttle_controller_params: [
        16.0, #p_gain
        0.005, #i_gain
        50.0, #d_gain

        -10.0, # output_lim_lower, absolute value limit of output
        10.0, # output_lim_upper, absolute value limit of output
      ]

    braking_controller_params: [
        12.0, #p_gain
        0.005, #i_gain
        30.0, #d_gain

        0.0, # output_lim_lower, absolute value limit of output
        10.0, # output_lim_upper, absolute value limit of output
      ]
