car_interface: # Name of Module
  ros__parameters:
    update_rate: 33.33 #[ms]
    heartbeat_tolerance: 4.0
    heartbeat_modules: ["controls"]
    heartbeat_modules_accel: ["controls"]
    heartbeat_modules_inspection: ["controls"]
    testing: 1 #0 - no test, 1 - testing
