car_interface: # Name of Module
  ros__parameters:
    update_rate: 10.0 #[ms]
    ema_gain: 0.6
    heartbeat_tolerance: 4.0
    heartbeat_modules: [""]
    heartbeat_modules_accel: [""]
    heartbeat_modules_inspection: [""]
    heartbeat_modules_testing: [""]
    testing: 0 #0 - no test, 1 - testing
