ekf_node: # Name of Module
  ros__parameters:
    update_rate: 10.00 #[ms]
    slam_rate: 33.33 #[ms]
    # MAPPING MODE
    # 0: Full SLAM
    # 1: Only Localize
    # 2: No Localization or Mapping
    mapping_mode: 0
    ekf_on: 1
    current_state_pose_x: 0.0
    current_state_pose_y: 0.0
    imu_yaw: 0.0

build_graph_node: # Name of Module
  ros__parameters:
    update_rate: 100.00 #[ms]
    slam_rate: 33.33 #[ms]
    # MAPPING MODE
    # 0: Full SLAM
    # 1: Only Localize
    # 2: No Localization or Mapping
    mapping_mode: 0
    ekf_on: 1
    count_threshold: 5
    displacement_radius: 1.5
    loop_closed: false
    out_of_frame: -1
    cones_found: 0
    current_pose_id: 1000
    first_detection_pose_id: 0
    count: 0
    cones_potential: 0
    do_graph_slam: false
    close_loop_once_data: false
    transformStamped_header_frameid: "world"
    transformStamped_child_frameid: "child"
    transformStamped_translation_x: 0
    transformStamped_translation_y: 0
    transformStamped_translation_z: 0
    transformStamped_rotation_x: 0
    transformStamped_rotation_y: 0
    transformStamped_rotation_z: 0
    transformStamped_rotation_w: 1.0

compute_graph_node: # Name of Module
  ros__parameters:
    update_rate: 100.00 #[ms]
    slam_rate: 100.00 #[ms]
    # MAPPING MODE
    # 0: Full SLAM
    # 1: Only Localize
    # 2: No Localization or Mapping
    mapping_mode: 0
    ekf_on: 1

    P2P_ev1: 1200
    P2P_ev2: 1200
    P2P_ev3: 6000
    P2C_ev1: 60
    P2C_ev2: 600
    LoopClosure_ev1: 500
    LoopClosure_ev2: 500
    LoopClosure_ev3: 5000