name: UTFR DV24 Pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@0.7.0
        with:
          required-ros-distributions: humble
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@0.3.3
        with:
          package-name: example_package
          target-ros2-distro: humble
      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ros_ws/log
        if: always()
