name: UTFR DV24 Pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      # - name: Setup ssh key
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Setup ROS2
      #   uses: ros-tooling/setup-ros@0.7.0
      #   with:
      #     required-ros-distributions: humble
      # - name: Build and run tests
      #   uses: ros-tooling/action-ros-ci@0.3.3
      #   with:
      #     package-name: example
      #     target-ros2-distro: humble
      # - name: Upload Logs
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: colcon-logs
      #     path: log/
      # if: always()
      # - name: Bash cmd
      #   run: echo "${PWD}"
